parameters:
  sfex_user_list: '/data/user_list.json'

services:
  sfex_login_service:
    class: Symfonyextars\SimpleLogin\Service\SimpleLoginService
  sfex_login_check:
    class: Symfonyextars\SimpleLogin\Service\LoginChecker